### ISSUE TITLE
New container not creating books db file

### ISSUE THREAD

**Issue by turdona193** [linuxserver/docker-calibre-web#102]
## Expected Behavior
Running a new container without an existing book library. UID and GID both have permissions to read/write/execute to both volumes. Web Page launches successfully, but cannot do anything past there. I thought when I put '/books', it would create the library file.

## Current Behavior
Every time I try to provide a path to '/books', I get an error message 'DB Location is not Valid, Please Enter Correct Path' . When I click the button to navigate directories, nothing pops up.

## Steps to Reproduce

1. Grant full permissions to volumes via chown and chmod 777
2. Clear directories so no unexpected files exist.
3. Start calibre-web via docker-compose.
4. Try to enter '/books' as library location.

## Environment
**OS:** CentOS 7
**CPU architecture:** x86_64
**How docker service was installed:** I let docker compose pull the image from docker hub during the docker-compose up command.

## Command used to create docker container (run/create/compose/screenshot)
 Here is a copy of my compose file:
```
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=2224
      - PGID=2224
      - TZ=America/New_York
    volumes:
      - /opt/plex/data/calibreConfig:/config
      - /opt/plex/data/calibreBooks:/books
    ports:
      - 28083:8083
    restart: unless-stopped
```

## Docker logs

```
calibre-web    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
calibre-web    | [s6-init] ensuring user provided files have correct perms...exited 0.
calibre-web    | [fix-attrs.d] applying ownership & permissions fixes...
calibre-web    | [fix-attrs.d] done.
calibre-web    | [cont-init.d] executing container initialization scripts...
calibre-web    | [cont-init.d] 01-envfile: executing...
calibre-web    | [cont-init.d] 01-envfile: exited 0.
calibre-web    | [cont-init.d] 10-adduser: executing...
calibre-web    |
calibre-web    | -------------------------------------
calibre-web    |           _         ()
calibre-web    |          | |  ___   _    __
calibre-web    |          | | / __| | |  /  \
calibre-web    |          | | \__ \ | | | () |
calibre-web    |          |_| |___/ |_|  \__/
calibre-web    |
calibre-web    |
calibre-web    | Brought to you by linuxserver.io
calibre-web    | -------------------------------------
calibre-web    |
calibre-web    | To support LSIO projects visit:
calibre-web    | https://www.linuxserver.io/donate/
calibre-web    | -------------------------------------
calibre-web    | GID/UID
calibre-web    | -------------------------------------
calibre-web    |
calibre-web    | User uid:    2224
calibre-web    | User gid:    2224
calibre-web    | -------------------------------------
calibre-web    |
calibre-web    | [cont-init.d] 10-adduser: exited 0.
calibre-web    | [cont-init.d] 30-config: executing...
calibre-web    | cp: cannot stat '/app/calibre-web/gdrive.db': No such file or directory
calibre-web    | [cont-init.d] 30-config: exited 0.
calibre-web    | [cont-init.d] 99-custom-scripts: executing...
calibre-web    | [custom-init] no custom files found exiting...
calibre-web    | [cont-init.d] 99-custom-scripts: exited 0.
calibre-web    | [cont-init.d] done.
calibre-web    | [services.d] starting services
calibre-web    | [services.d] done.
```
