### ISSUE TITLE
 Container freezes on applying linuxserver/calibre-web:calibre files to container

### ISSUE THREAD

**Issue by jorritsmit** [linuxserver/docker-calibre-web#105]
## Expected Behavior
Container should start

## Current Behavior
Container freezes on init during the step where it applies the docker mods

## Steps to Reproduce
1. Setup container in docker-compose with docker mods (latest image version-0.6.9)
2. Start container

## Environment
**OS:** 5.4.72-1-MANJARO
**CPU architecture:** x86_64
**How docker service was installed:** From distro repo

## Command used to create docker container (run/create/compose/screenshot)
```
 calibreweb:
    image: 'linuxserver/calibre-web'
    container_name: 'calibreweb'
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
      - 'DOCKER_MODS=linuxserver/calibre-web:calibre'
    volumes:
      - '${DISK_PATH}/calibre/calibreweb/:/config'
      - '${DISK_PATH}/calibre/library:/books'
    # ports:
    #   - 8083:8083
    # entrypoint:
    #   - /config/docker-entrypoint.sh
    labels:
      - traefik.http.routers.calibreweb.entrypoints=websecure
      - traefik.http.routers.calibreweb.tls.certresolver=default
      - traefik.http.routers.calibreweb.tls=true
      - traefik.http.routers.calibreweb.middlewares=chain-secure@file
    healthcheck:
      test: curl -f http://localhost:8083
      interval: 1m
      timeout: 30s
      retries: 3
    restart: unless-stopped
```

## Docker logs
Attaching to calibreweb
calibreweb      | 2020-11-04T08:49:59.953737949Z [mod-init] Attempting to run Docker Modification Logic
calibreweb      | 2020-11-04T08:50:00.057432255Z [mod-init] Applying linuxserver/calibre-web:calibre files to container
