### ISSUE TITLE
Please update sqlite to 3.31.1.

### ISSUE THREAD

**Issue by BoneAsh** [linuxserver/docker-calibre-web#108]
I delete book error. [https://github.com/janeczku/calibre-web/issues/1639](https://github.com/janeczku/calibre-web/issues/1639), please update sqlite to 3.31.1 to resolve it.

**Comment by jackhadrill** [comment]
## Expected Behavior
When a book is deleted using the web UI, it should be deleted from both the disk and the calibre databse.

## Current Behavior
The book is only deleted from disk. It persists in the database and will continue to display on the web UI.

## Steps to Reproduce
1. Remove book using web UI.

## Identified Fix
Update SQLite to 3.31.1 (or update Ubuntu to 20.04)/

## Environment
**OS:**  N/A
**CPU architecture:** x86_64
**How docker service was installed:** Docker CE 

## Command used to create docker container (run/create/compose/screenshot)
```yaml
version: "3.0"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /opt/config:/config
      - /opt/books:/books
    ports:
      - 8083:8083
```
