### ISSUE TITLE
Arm64: Exec format error

### ISSUE THREAD

**Issue by catsout** [linuxserver/docker-calibre-web#113]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

run ok  

## Current Behavior

start failed

## Steps to Reproduce

1. docker-compose up

## Environment
**OS:** debian-sid
**CPU architecture:** arm64
**How docker service was installed:** `sudo apt install docker.io`

## Command used to create docker container (run/create/compose/screenshot)

```yaml
---
version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
        #      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /home/<user>/.config/calibre-web:/config
      - /home/<user>/Documents/books:/books
    ports:
      - 6803:8083
    restart: unless-stopped
```

## Docker logs

```sh
calibre-web    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
calibre-web    | [s6-init] ensuring user provided files have correct perms...exited 0.
calibre-web    | [fix-attrs.d] applying ownership & permissions fixes...
calibre-web    | [fix-attrs.d] done.
calibre-web    | [cont-init.d] executing container initialization scripts...
calibre-web    | [cont-init.d] 01-envfile: executing... 
calibre-web    | foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/01-envfile: Exec format error
calibre-web    | [cont-init.d] 01-envfile: exited 127.
calibre-web    | [cont-init.d] 10-adduser: executing... 
calibre-web    | foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/10-adduser: Exec format error
calibre-web    | [cont-init.d] 10-adduser: exited 127.
calibre-web    | [cont-init.d] 30-config: executing... 
calibre-web    | foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/30-config: Exec format error
calibre-web    | [cont-init.d] 30-config: exited 127.
calibre-web    | [cont-init.d] 99-custom-scripts: executing... 
calibre-web    | foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/99-custom-scripts: Exec format error
calibre-web    | [cont-init.d] 99-custom-scripts: exited 127.
calibre-web    | [cont-init.d] done.
calibre-web    | [services.d] starting services
calibre-web    | s6-supervise (child): fatal: unable to exec run: Exec format error
calibre-web    | s6-supervise calibre-web: warning: unable to spawn ./run - waiting 10 seconds
calibre-web    | [services.d] done.
calibre-web    | s6-supervise (child): fatal: unable to exec run: Exec format error
calibre-web    | s6-supervise calibre-web: warning: unable to spawn ./run - waiting 10 seconds
```

## Other
I also build it, but the same error. It looks like the file failed to exec is come from the base image.

### cpu
amlogic [s905x3](https://www.cnx-software.com/2019/04/12/amlogic-s905x3-specifications-block-diagram/)
