### ISSUE TITLE
Docker stops responding on saving anything in web interface

### ISSUE THREAD

**Issue by iamdoubz** [linuxserver/docker-calibre-web#137]
## Expected Behavior
**Example 1 (E1)**: In the admin interface, I added the permission of "View eBooks" and clicked "Save". Should save and I keep adding users, etc.
**Example 2 (E2)**: While editing metadata for a book, I add some cover art, tags, and click save. It should save the data and I keep going through my books, etc.

## Current Behavior
**E1**: I save, and webpage spins, and spins, and spins, and I cannot do anything until I restart the docker container.
**E2**: I click on Save, and the webpage spins, and spins, and spins, and I cannot do anything until I restart the docker container.

### How I installed docker-calibre-web by linuxserver
1. `git clone https://github.com/linuxserver/docker-calibre-web.git`
2. `cd docker-calibre-web`
3. `nano docker-compose.yml`
```yml
---
version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /var/lib/calibre-web/config:/config
      - /var/lib/calibre-web/books:/books
    ports:
      - 8083:8083
    restart: always
```
4. Start container: `sudo docker-compose up -d`
5. Navigate to http://localhost:8083/
6. Add /books as library
7. Log in as default `admin:admin123`

### Reproduce
1. Upload a book OR
2. Change permissions on admin user OR
3. Edit metadata for any book
4. AND must have Google Drive enabled

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:**
[Using this guide from Docker](https://docs.docker.com/engine/install/ubuntu/).

## Command used to create docker container (run/create/compose/screenshot)
`sudo docker-compose up -d`
```yml
---
version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /var/lib/calibre-web/config:/config
      - /var/lib/calibre-web/books:/books
    ports:
      - 8083:8083
    restart: always
```

## Docker /var/lib/calibre-web/config/calibre-web.log
```
[2021-04-13 12:08:53,547]  INFO {cps.server:216} webserver stop (restart=True)
[2021-04-13 12:08:54,563]  INFO {cps.server:201} Performing restart of Calibre-Web
[2021-04-13 12:08:55,885]  INFO {cps:101} Starting Calibre Web...
[2021-04-13 12:08:55,983]  INFO {cps.server:146} Starting Gevent server on [::]:8083
[2021-04-13 12:14:30,574]  INFO {cps.ub:721} Book 1 readbit toggled
[2021-04-13 12:14:31,682]  INFO {cps.ub:721} Book 1 readbit toggled
[2021-04-13 12:14:50,613] ERROR {cps.gdriveutils:200} Google Drive error: No credential to refresh.
[2021-04-13 12:14:50,613] ERROR {cps.gdriveutils:212} Google Drive error: No credential to refresh.
[2021-04-13 12:19:12,811]  INFO {cps.server:216} webserver stop (restart=False)
```

## Docker logs
Will provide if needed.

## Extra

| **Program Library** | **Installed Version** |
| ---: | :--- |
| Platform | Linux 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 |
| Python | 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0] |
| Calibre_Web | 0.6.11 - 4a4d02ea6a91ba3e77337cfce65e756e2e806599 - 2021-02-02T19:04:55+01:00 |
| ebook converter | ebook-convert (calibre 5.14.0) |
| unrar | UNRAR 5.61 beta 1 freeware Copyright (c) 1993-2018 Alexander Roshal |
| kepubify | kepubify v3.1.6 |
