### ISSUE TITLE
reverse proxy with traefik

### ISSUE THREAD

**Issue by bcg62** [linuxserver/docker-calibre-web#17]
anyone been able to do this? running calibre in rancher and no matter what settings i've tired i cant match the nginx example.

exposing a way to somehow pass `--url-prefix` to calibre would make this easier

**Comment by bcg62** [comment]
it does.

https://manual.calibre-ebook.com/generated/en/calibre-server.html

as already mentioned it’s the —url-prefix option

**Comment by homerr** [comment]
Could you give us a little more information on how you're trying to set this up? For example, are you trying to access calibre-web via a path (https://something.tld/calibre) or through a dedicated subdomain (https://calibre.something.tld) we could also do with your traefik labels and we can go from there.

**Comment by j0nnymoe** [comment]
The container is using this: https://github.com/janeczku/calibre-web are these different applications?

**Comment by sparklyballs** [comment]
@j0nnymoe totally different

calibre server is part of calibre itself whereas calibre-web is a separate app used in conjunction with calibre

basically @bcg62 , any options on that link are not for this app

**Comment by j0nnymoe** [comment]
@sparklyballs thanks for clearing that up, that's what I suspected.

**Comment by rparree** [comment]
Does this mean there's no way of using using a reverse proxy with a prefix:

```yaml
calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    ports:
       - 8083:8083
    volumes:
      - ./calibre-config:/config
      - /home/rparree/nextcloud/calibre:/books
    labels:
          - "traefik.enable=true"
          - "com.centurylinklabs.watchtower.enable=true"
          - "traefik.http.routers.calibre.rule=PathPrefix(`/calibre`)"
          - "traefik.http.services.calibre.loadbalancer.server.port=8083"
```

tx
