### ISSUE TITLE
Latest image (0.6.14) is missing /usr/bin/ebook-convert

### ISSUE THREAD

**Issue by iicky** [linuxserver/docker-calibre-web#170]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The latest image of calibre-web (version 0.6.14) is missing the `/usr/bin/ebook-convert` tool, causing conversion to fail. I am running the image using docker compose with the ENV variable `DOCKER_MODS=linuxserver/calibre-web:calibre`. Rolling back to version 0.6.13 fixes the issue.

Is this tool being removed in newer versions or is this a bug? If the tool is being removed, what is recommended as an alternative?

------------------------------

## Expected Behavior

The tool `/usr/bin/ebook-convert` should exist in the image.

## Current Behavior

The tool `/usr/bin/ebook-convert` does not exist in the latest image, but exists in previous versions.

## Steps to Reproduce

1. Deploy latest image version using docker-compose:
```
version: "3.7"
services:
  calibre:
    container_name: calibre
    image: linuxserver/calibre-web
    ports:
      - 8083:8083
    volumes:
      - /path-to-config:/config
      - /path-to-books:/books
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=MY_TZ
      - DOCKER_MODS=linuxserver/calibre-web:calibre
```

2.  Look for `/usr/bin/ebook-convert`, nothing there:
```
docker exec -it calibre ls /usr/bin/ebook-convert
ls: cannot access '/usr/bin/ebook-convert': No such file or directory
```

3. Swap to image `linuxserver/calibre-web:0.6.13` and search for it again - its there:

```
docker exec -it calibre ls /usr/bin/ebook-convert
/usr/bin/ebook-convert
```

## Environment
**OS:  Ubuntu 20.04.3 LTS**
**CPU architecture:** x86_64
**How docker service was installed:**

Image is pulled from `linuxserver/calibre-web`.

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up -d` with the compose example above.
## Docker logs

N/A
