### ISSUE TITLE
Browser Reader Does Not Open New Tab in Firefox

### ISSUE THREAD

**Issue by ModestTG** [linuxserver/docker-calibre-web#171]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When using the "Read in Browser" feature, a new tab is opened for reading. This is currently happening in Google Chrome.

## Current Behavior
When using the "Read in Browser" feature in Firefox, a new tab is not opened. Due to the way this feature works, you can only feasibly get back to the main Calibre-web display by re-entering the Calibre-web URL (or deleting all of the URL parameters). Using the Back feature in the web browser doesn't reliably work as a new URL is called for every action you make while in the reader. This issue seems to be specific to epub or other similar formats. As a workaround, I have books that are in PDF format, which allow me to hit Back and get back to the main screen.

## Steps to Reproduce

1. Open Calibre-web in Firefox
2. Start reading a book with "Read in Browser", select epub or similar format
3. Once in the book, you cannot navigate back to the Calibre-web main page without putting in the main page URL.

## Environment
**OS:** Linux esxi-docker1 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
**CPU architecture:** x86_64
**How docker service was installed:**

From the official docker repository on Docker Hub

## Command used to create docker container (run/create/compose/screenshot)

Docker Compose
```yaml
version: "3.7"
services:
  calibre:
    image: linuxserver/calibre:latest
    container_name: Calibre
    restart: unless-stopped
    networks:
      - network
    ports:
      - "8088:8080"
      - "8089:8081"
    volumes:
      - "/mnt/plex/Books:/config"
      - "/home/docker/container_data/calibre/bookdump:/bookdump"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - GUAC_USER=$GUAC_USER
      - GUAC_PASS=$GUAC_PASS
  calibre-web-textbooks:
    image: linuxserver/calibre-web
    container_name: Calibre-web-textbooks
    restart: unless-stopped
    networks:
      - network
    ports:
      - "8085:8083"
    volumes:
      - "/mnt/docker/container_data/calibre-web/config:/config"
      - "/mnt/plex/Books/Textbooks:/textbooks"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
networks:
  network:
    driver: bridge
```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1020
User gid:    1002
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
