### ISSUE TITLE
ebook-convert - Missing from bin location

### ISSUE THREAD

**Issue by LukeG20** [linuxserver/docker-calibre-web#209]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The ebook-convert file needed for general book conversion is missing from the documented location. Resulting in all conversion requests failing.

I have tried putting said file back in manually but it's removed on restart and it caused issues with permissions aswell. I've also tried to put the file in another persistent location but it seems hardcoded to be in "/usr/bin/".

------------------------------

## Expected Behavior
As documented, I would expect the ebook-convert file to be present.

## Current Behavior
Missing file and conversion failure

## Environment
**OS:TrueNAS Scale**
**CPU architecture:**rm64
**How docker service was installed:**
apps available from the "store" within TrueNAS Scale

**Comment by drizuid** [comment]
You listed your cpu as arm64 and our readme states that ebook-convert is x86_64 only.  While we know the issue here, for future reference, please ensure you provide your docker run or docker compose.

**Comment by LukeG20** [comment]
> You listed your cpu as arm64 and our readme states that ebook-convert is x86_64 only. While we know the issue here, for future reference, please ensure you provide your docker run or docker compose.
> 
> it has been brought to my attention that scale only supports amd64 also, so there is something fishy with your environment info

@drizuid thanks for the reply, my CPU is a AMD Ryzen™ 5 3600 and worked fine before I updated to the latest version of calibre_web, which seems to be missing the necessary file to assign in external binaries. I have checked other issues on here and I can see people have reported similar issues.

Could the issue be attributed to the move from `DOCKER_MODS=linuxserver/calibre-web:calibre` to `DOCKER_MODS=linuxserver/mods:universal-calibre`?

My docker compose is below, this is what I used on my Synology NAS to confirm if it was an issue with Scale but its also missing the necessary file for ebook-convertion. Looking at an older backup I have the "ebook-convert" files there.

```
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    networks:
      - proxy
    volumes:
      - /volume1/docker/Calibre-Web/config:/config
      - /volume1/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
networks:
  proxy:
    external: true
```
