### ISSUE TITLE
Calibre-web - conversion from epub to kepub fails

### ISSUE THREAD

**Issue by psyciknz** [linuxserver/docker-calibre-web#211]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Converting a book on calibre-web in the tasks it says failed.  When I look at the logs I see:
```
[2022-10-19 15:45:56,133] DEBUG {cps.tasks.convert:208} [  1/  1] Converting /books/MyAuthor/[F05]_MyBook (756)/[F05]_MyBook - MyAuthor.epub
[2022-10-19 15:45:56,133] DEBUG {cps.tasks.convert:208} 1 total: 1 converted, 0 copied, 0 skipped, 0 errored
[2022-10-19 15:45:56,141]  INFO {cps.tasks.convert:188} ebook converter failed with error while converting book
[2022-10-19 15:45:56,141] ERROR {cps.tasks.convert:192} Converted file not found or more than one file in folder /books/MyAuthor/[F05]_MyBook (756)
```

**Redacted author/bookname**

## Current Behavior

When I look at that directory in question I do see a converted file.   So the binaries look like they've been hooked up properly...but something after the conversion is not picking up the new file has been created.

I see the filename [F05] MyBook - MyAuthor_Converted.kepub.epub

## Steps to Reproduce

1.   Navigate to book
2.   Edit Metadata
3.    Choose Convert from epub
4.    Choose convert to kepub
5.    View logs (failed)
6.    View file system, see [F05] MyBook - MyAuthor_Converted.kepub.epub
7.    Tried epub to mobi as well, also failed - it could be due to a DB is locked error which I can't work out (I can exec into the container and copy the existing db to a new file with no issues.....not sure what user the container is running under.
8. 
## Environment
**OS:**  ubuntu
**CPU architecture:** x86_64/arm32/arm64 amd64
**How docker service was installed:** can't remember official docker repo  I think

## Command used to create docker container (run/create/compose/screenshot)

compose.
```
  calibre:
    container_name: calibre
    image: ${LINUXSERVER}/calibre-web:latest
    restart: always
    mem_limit: 120m
    environment:
      - TZ=Pacific/Auckland
      - PUID=1000
      - PGID=1000
      - BASEPATH=/hdd/docker-data
      - SERVERFOLDERS=/media/serverfolders
      - HDDBASEPATH=/hdd
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    env_file:
      - .env
    healthcheck:
      # I tried adding '&& exit 1',  '|| exit `' it doesn't work.
      test: bash -c "test  -f  /books/metadata.db && exit 0 || exit 1"
      interval: 5m
      timeout: 30s
      retries: 20
    labels:
      - autoheal=true
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - media
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${CALIBRE_LIBRARY}:/books
      - ${BASEPATH}/media/calibre/:/config
    ports:
      - "8087:8083"
```
## Docker logs

Fragment above and also:
```
[2022-10-19 16:27:47,002] ERROR {cps.editbooks:226} Database error: (sqlite3.OperationalError) database is locked
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-10-19 16:30:13,217] DEBUG {cps.updater:329} Stable version: {'version': '0.6.19'}
```

On trying to update book metadata
