### ISSUE TITLE
DB Location is not Valid, Please Enter Correct Path

### ISSUE THREAD

**Issue by r00t9** [linuxserver/docker-calibre-web#213]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I cannot setup the DB, i try with volume with out any volume nothing work to find DB
------------------------------

## Expected Behavior
To find default DB

## Current Behavior
Not find anything

## Steps to Reproduce
try run docker-composer

## Environment
**OS: Ubuntu 22.04 LTS Server
**CPU architecture:** x86_64
**How docker service was installed:**
from the official docker repo, from the distro repo

## Command used to create docker container (run/create/compose/screenshot)
```
---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
#    volumes:
#      - /opt/linuxserer/calibre/config:/config-vol
#      - /opt/linuxserver/calibre/library:/book-vol
    ports:
      - 8083:8083
    restart: unless-stopped
```

## Docker logs
check file
[calibre_docker.log](https://github.com/linuxserver/docker-calibre-web/files/9843809/calibre_docker.log)
