### ISSUE TITLE
Release LS180 broke startup - I'm getting a Runtime Error immediately on start with version LS180 and above

### ISSUE THREAD

**Issue by ahughes03** [linuxserver/docker-calibre-web#215]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Calibre-Web should start

## Current Behavior

Calibre-Web doesn't start, I immediately get a runtime error that loops. This error is fixed when I revert to LS179 and before.

## Steps to Reproduce

1. If I revert to LS179 and before, Calibre-Web starts as expected
2. Beginning with LS180, Calibre-Web will not start

## Environment
**OS:** Ubuntu 20.04LTS
**CPU architecture:** x86_64
**How docker service was installed:** From the official Docker repo

## Command used to create docker container (run/create/compose/screenshot)
 Created via a docker-compose

```
---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /opt/appdata/calibre-web:/config
      - /mnt/downloads/books/Calibre Library/Calibre:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

## Docker logs

```
    
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[custom-init] No custom files found, skipping...
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
That error loops repeatedly, there is nothing different in the logs after that Traceback.

I'll upgrade from 20.04 to 22.04 to see if LS180's update to Jammy is the issue here.
