### ISSUE TITLE
calibre-web fails to start beginning with 0.6.19

### ISSUE THREAD

**Issue by geekifier** [linuxserver/docker-calibre-web#221]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
The calibre-web app starts successfully when using the latest image (0.6.19).

## Current Behavior

The application fails to start with following in the logs:

```
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

[the above traceback repeats over and over]
```

## Steps to Reproduce

Update the `docker-compose.yml` to use the following image: `lscr.io/linuxserver/calibre-web:amd64-version-0.6.19 `.

Revert back to `0.6.18` and the application starts fine.

## Environment
**OS:** Ubuntu 16.04.7 LTS, kernel: 4.4.0-92-generic
**CPU architecture:**  x86_64
**How docker service was installed:** Ubuntu's repo 
`docker-ce/xenial,now 5:20.10.7~3-0~ubuntu-xenial amd64 [installed]`.
`Docker version 20.10.7, build f0df350`

## Command used to create docker container (run/create/compose/screenshot)

```yaml
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:amd64-version-0.6.19
    container_name: calibre-web
    environment:
      - PUID=117
      - PGID=123
      - TZ=America/Indiana/Indianapolis
    volumes:
      - /opt/calibre-web:/config
      - /mnt/blackhole_public/Library/Calibre:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

## Docker logs
```
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    117
User gid:    123
-------------------------------------

[custom-init] No custom files found, skipping...
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 26, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 124, in create_app
    updater_thread.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

[the above traceback repeats over and over]
```
