### ISSUE TITLE
[BUG] K8s secret gmail.json - start failed

### ISSUE THREAD

**Issue by mmalyska** [linuxserver/docker-calibre-web#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I've mounted `gmail.json` from `Secret` to `/config/gmail.json` it is mounted as readonly and container is not starting because it cannot chown this file.

### Expected Behavior

Container starting properly.

### Steps To Reproduce

Create k8s deployment with mounted volume from secret to mount file `/config/gmail.json`
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: gmail-secret
  namespace: calibre
data:
  gmail: someJsonHere
```

and then in deployment
```yaml
...
spec:
  template:
    spec:
      containers:
        - ...
          volumeMounts:
          - mountPath: /config/gmail.json
              name: gmail
              subPath: gmail
volumes:
  - name: gmail
    secret:
      defaultMode: 420
      secretName: gmail-secret
```

### Environment

```markdown
- OS: K8S worker
```

### CPU architecture

x86-64

### Container logs

```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/mods:universal-calibre files to container
[mod-init] linuxserver/mods:universal-calibre applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1001
User GID:    1001
───────────────────────────────────────

chown: changing ownership of '/config/gmail.json': Read-only file system
s6-rc: warning: unable to start service init-calibre-web-config: command exited 1
```
