### ISSUE TITLE
[BUG] DB Location is not Valid, Please Enter Correct Path

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [linuxserver/docker-calibre-web#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

fresh installed application if used /books like recommeded
in UI Database Configuration -> Location of Calibre Database

show **DB Location is not Valid, Please Enter Correct Path**

### Expected Behavior

Have to work normally 

### Steps To Reproduce

1. docker 
2. docker-compose.yml
```
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web:0.6.20
    container_name: calibre-web
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Europe/Amsterdam
#      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
#      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./conf/calibre:/config
      - ./data/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- How docker service was installed: Like described here : https://docs.docker.com/engine/install/debian/
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose pull 
docker-compose up -d
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    2000
User GID:    2000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
