### ISSUE TITLE
add option to import books from a folder

### ISSUE THREAD

**Issue by vampywiz17** [linuxserver/docker-calibre-web#259]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I make a docker stack, to import books to my database. It work well, but would be good to somehow build it to calibre-web.

### Reason for change

usefull, if you use readarr, or similar programs and not need to install calibre container.

```
version: "3"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - calibre-web
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1005
      - TZ=$TZ
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - $APPDATA_PATH/calibre-web:/config
      - /mnt/adat/Torrent/Books:/mnt/adat/Torrent/Books
      - /mnt/adat/Torrent/Books_calibre-web:/books
    ports:
      - 8083:8083
    restart: unless-stopped
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.import_book.schedule: "@every 10m"
      ofelia.job-exec.import_book.command: "/app/calibre/calibredb add -r /mnt/adat/Torrent/Books --with-library /books"
      ofelia.job-exec.set_rights.schedule: "@every 10m"
      ofelia.job-exec.set_rights.command: "/usr/bin/chown -R 1000:1005 /books"
```
