### ISSUE TITLE
Does it work with traefik or do I have misconfigurations ?

### ISSUE THREAD

**Issue by thepenguinthatwants** [linuxserver/docker-calibre-web#43]
Hiya!

I am trying to get this work with my traefik setup. For now I am trying it on my localhost.

Location of Calibre database I put  /books
and it either gives me: Sometimes I get DB location is not valid, please enter correct path or it works but I get 403 Forbidden error

The docker-compose file is this
```
version: '3'

services:
  calibre-web:
    image: linuxserver/calibre-web
    restart: unless-stopped
    networks:
      - srv
    volumes:
      - './books:/books'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      PGID: '1000'
      PUID: '1000'
    labels:
      - traefik.enable=true
      - traefik.backend=calibre-web
      - traefik.frontend.rule=Host:calibre.localhost
      - traefik.docker.network=srv
      - traefik.port=8083

networks:
  srv:
    external: true
```

Inside the books folder I have metadata.db which my local calibre has created.
