### ISSUE TITLE
Calibre failed with error: /app/calibre/bin/pdftohtml: error while loading shared libraries: libnss3.so: cannot open shared object file

### ISSUE THREAD

**Issue by itsthejb** [linuxserver/docker-calibre-web#55]
## Expected Behavior

- Can convert PDF to ePub/Mobi

## Current Behavior

```
[2019-10-23 09:31:06,310] ERROR in worker: Calibre failed with error: /app/calibre/bin/pdftohtml: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

## Steps to Reproduce
- Unsure. Some feature of the PDF? Here it is: https://web.mit.edu/alexmv/6.037/sicp.pdf

## Environment
**OS:** Centos7     
**CPU architecture:** x86_64

## Command used to create docker container (run/create/compose/screenshot)

```
  calibre:
    container_name: calibre
    image: linuxserver/calibre-web:latest
    volumes:
      - /docker/appdata/calibre:/config
      - /.storage.cached/Media/Books:/books
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    env_file:
      - media.env
    networks:
      - shared
    restart: always
    healthcheck:
      test: /bin/s6-svstat /var/run/s6/services/calibre-web
      interval: 1m
      timeout: 5s
      retries: 3
```

## Docker logs

```
[2019-10-23 09:31:03,853] INFO in worker: Book id 30 - target format of .epub does not exist. Moving forward with convert.
[2019-10-23 09:31:06,309] INFO in worker: ebook converter failed with error while converting book
[2019-10-23 09:31:06,310] ERROR in worker: Calibre failed with error: /app/calibre/bin/pdftohtml: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

**Comment by hholst80** [comment]
Try installing libnss3 in the container.

**Comment by hholst80** [comment]
Consider the dependencies in Debian there might be additional packages that needs to be installed.

https://www.preining.info/blog/2019/10/state-of-calibre-in-debian/

**Comment by itsthejb** [comment]
See https://github.com/linuxserver/docker-calibre-web/pull/56

**Comment by LostOnTheLine** [comment]
> ## Command used to create docker container (run/create/compose/screenshot)
> ```yaml
>   calibre:
>     container_name: calibre
>     image: linuxserver/calibre-web:latest
>     volumes:
>       - /docker/appdata/calibre:/config
>       - /.storage.cached/Media/Books:/books
>       - /etc/localtime:/etc/localtime:ro
>     environment:
>       - DOCKER_MODS=linuxserver/calibre-web:calibre
>     env_file:
>       - media.env
>     networks:
>       - shared
>     restart: always
>     healthcheck:
>       test: /bin/s6-svstat /var/run/s6/services/calibre-web
>       interval: 1m
>       timeout: 5s
>       retries: 3
> ```

I was trying to find a HealthCheck for Calibre-Web & came across this, as of 2023/02/25 is does not work, says ***[Unhealthy]** when the container is working correctly. Not sure if that is related to the issue or not but at least for future searchers it should be noted

**Comment by itsthejb** [comment]
@LostOnTheLine Not related - this will have happened because linuxserver seem to have been migrating the location of their s6 services. For example, the calibre-web service file now lives at `/var/run/service/svc-calibre-web`, so the healthcheck becomes `s6-svstat /var/run/service/svc-calibre-web`.

As for `libnss3`, it's nowadays possible and far better to install it with 

```
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libnss3
```

**Comment by LostOnTheLine** [comment]
> s6-svstat /var/run/service/svc-calibre-web

Thanks, that seems to work.
```yaml

    healthcheck:
    #  test: /bin/s6-svstat /var/run/s6/services/calibre-web
      test: s6-svstat /var/run/service/svc-calibre-web
      interval: 1m
      timeout: 5s
      retries: 3
```
