### ISSUE TITLE
Cannot open pdfs in Chrome: An error occured while loading the PDF

### ISSUE THREAD

**Issue by jeygith** [linuxserver/docker-calibre-web#72]
## Expected Behavior
PDF books should open in Chrome

## Current Behavior
An error occurred while loading the PDF.
PDF.js v2.2.228 (build: d7afb74a)
Message: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".
![Screenshot 2020-04-17 at 10 43 47](https://user-images.githubusercontent.com/12443889/79545702-cc0d5980-8099-11ea-81de-aefba55603a6.png)

## Steps to Reproduce
1. Open PDF book in library 
2. Read in Browser
3. Select pdf
4. Error is thrown in the new tab

## Environment
**OS:**     Centos8 4.18.0-147.5.1.el8_1.x86_64
**CPU architecture:** x86_64 
**Docker** version 19.03.8, build afacb8b
**docker-compose** version 1.25.0, build 0a186604
**Browser** Chrome Version 81.0.4044.92 (Official Build) (64-bit) 
**How docker service was installed:**  docker-compose up    

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ./config:/config
      - /books:/books
      - /docker/calibre/config/CalibreLibrary:/library
    ports:
      - 8083:8083
    restart: unless-stopped
```

## Docker logs
1. [docker-logs.log](https://github.com/linuxserver/docker-calibre-web/files/4491773/docker-logs.log)
2. no errors in the `/app/calibre-web/calibre-web.log` 
```
[2020-04-17 06:16:51,669]  INFO {cps:89} Starting Calibre Web...
[2020-04-17 06:16:51,765]  INFO {cps.server:140} Starting Gevent server on [::]:8083

```
