### ISSUE TITLE
Can't read metadata when uploading epub

### ISSUE THREAD

**Issue by scambra** [linuxserver/docker-calibre-web#74]
## Expected Behavior

Uploading a epub displays title, author and other metadata available in epub.

## Current Behavior

Uploading epub display metadata form empty, only title filled with filename

## Environment
**OS:**  Raspbian buster
**CPU architecture:** arm32      
**How docker service was installed:**      
Using dockstarter

## Command used to create docker container (run/create/compose/screenshot)

Extract from docker-compose.yml:
```yaml
  calibreweb:
    container_name: calibreweb
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    hostname: ${DOCKERHOSTNAME}
    image: linuxserver/calibre-web
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
    - ${CALIBREWEB_PORT_8083}:8083
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/calibreweb:/config
    - ${DOCKERSHAREDDIR}:/shared
    - ${MEDIADIR_BOOKS}:/books
```

## Docker logs
Starting calibreweb displays these errors:

[2020-04-26 19:08:51,707] {/app/calibre-web/cps/book_formats.py:55} WARNING - cannot import epub, extracting epub metadata will not work: libxslt.so.1: cannot open shared object file: No such file or directory
[2020-04-26 19:08:51,711] {/app/calibre-web/cps/book_formats.py:62} WARNING - cannot import fb2, extracting fb2 metadata will not work: libxslt.so.1: cannot open shared object file: No such file or directory

## Workaround

Install libxlst1.1 inside docker instance, and restart calbre-web, then uploads extract metadata from epub and displays it in form after uploading file.
