### ISSUE TITLE
Caliblur theme, messed up cover image border

### ISSUE THREAD

**Issue by lightmaster** [linuxserver/docker-calibre-web#98]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

On a book's page, the cover border should be resized to fit around the image of the cover

## Current Behavior

All books' covers are shown with the black border as a landscape rectangle that does not actually wrap around the cover's image.
![Caliblur border issue](https://i.postimg.cc/dvmxPYxf/Calibre-web-Calibur-Cover-Border-issue.png)
## Steps to Reproduce

1. Set theme to Caliblur
2. Navigate to any book with a cover image

## Environment
**OS:**      Synology DSM 6.2
**CPU architecture:** x86_64    
**How docker service was installed:**      

Docker came installed on Synology DSM

## Command used to create docker container (run/create/compose/screenshot)

docker-compose.yml:
```
version: "3.5"

services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    volumes:
      - "./config:/config"
      - "../../books/calibre:/Books"
    environment:
      - "PUID=1029"
      - "PGID=65538"
      - "TZ=America/New_York"
      - "DOCKER_MODS=linuxserver/calibre-web:calibre"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: host
    restart: unless-stopped
```

## Docker logs

No errors generated.
